<?php

return [
    'site_url'                  => '',
    'site_name'                 => 'Blessing Skin',
    'site_description'          => 'Open-source PHP Minecraft Skin Hosting Service',
    'user_can_register'         => 'true',
    'register_with_player_name' => 'true',
    'require_verification'      => 'false',
    'regs_per_ip'               => '3',
    'ip_get_method'             => '0',
    'api_type'                  => 'false',
    'announcement'              => 'Welcome to Blessing Skin {version}!',
    'color_scheme'              => 'skin-blue',
    'home_pic_url'              => './public/bg.jpg',
    'custom_css'                => '',
    'custom_js'                 => '',
    'player_name_rule'          => 'official',
    'custom_player_name_regexp' => '',
    'player_name_length_min'    => '3',
    'player_name_length_max'    => '16',
    'comment_script'            => '',
    'allow_sending_statistics'  => 'true',
    'user_initial_score'        => '1000',
    'sign_gap_time'             => '24',
    'sign_score'                => '10,100',
    'score_per_storage'         => 'true',
    'private_score_per_storage' => '10',
    'return_score'              => 'true',
    'score_per_player'          => '100',
    'sign_after_zero'           => 'false',
    'version'                   => '',
    'copyright_text'            => '<strong>Copyright &copy; '.getdate()['year'].' <a href="{site_url}">{site_name}</a>.</strong> All rights reserved.',
    'auto_del_invalid_texture'  => 'false',
    'allow_downloading_texture' => 'true',
    'texture_name_regexp'       => '',
    'return_204_when_notfound'  => 'false',
    'cache_expire_time'         => '31536000',
    'max_upload_file_size'      => '1024',
    'force_ssl'                 => 'false',
    'auto_detect_asset_url'     => 'true',
    'plugins_enabled'           => '',
    'copyright_prefer'          => '0',
    'score_per_closet_item'     => '0',
    'favicon_url'               => 'public/favicon.ico'
];
