<?php

namespace App\Providers;

use App\Services;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->singleton('cipher', 'App\Services\Cipher\\'.config('secure.cipher'));
        $this->app->singleton(Services\Option::class);
        $this->app->alias(Services\Option::class, 'options');
    }

    public function boot(Request $request): void
    {
        Paginator::useBootstrap();

        $this->configureMail();
        $this->configureUrlGenerator($request);
    }

    protected function configureMail(): void
    {
        config([
            'mail.default' => option('mail_mailer', env('MAIL_MAILER')) ?: 'smtp',
            'mail.mailers.smtp.host' => option('mail_host', env('MAIL_HOST')) ?: 'smtp.mailgun.org',
            'mail.mailers.smtp.port' => option('mail_port', env('MAIL_PORT')) ?: 587,
            'mail.mailers.smtp.username' => option('mail_username', env('MAIL_USERNAME')),
            'mail.mailers.smtp.password' => option('mail_password', env('MAIL_PASSWORD')),
            'mail.mailers.smtp.encryption' => option('mail_encryption', env('MAIL_ENCRYPTION', 'tls')),
            'mail.from.address' => option('mail_from_address', env('MAIL_FROM_ADDRESS')) ?: 'hello@example.com',
            'mail.from.name' => option('mail_from_name', env('MAIL_FROM_NAME')) ?: config('app.name', 'Example'),
        ]);
    }

    /**
     * Control the URL generated by url() function.
     *
     * @codeCoverageIgnore
     */
    protected function configureUrlGenerator(Request $request): void
    {
        if (!option('auto_detect_asset_url')) {
            $rootUrl = option('site_url');

            // Replace HTTP_HOST with site_url set in options,
            // to prevent CDN source problems.
            if (URL::isValidUrl($rootUrl)) {
                URL::forceRootUrl($rootUrl);
            }
        }

        /**
         * Check whether the request is secure or not.
         * True is always returned when "X-Forwarded-Proto" header is set.
         *
         * We define this function because Symfony's "Request::isSecure()" method
         * needs "setTrustedProxies()" which sucks when load balancer is enabled.
         */
        $isRequestSecure = $request->server('HTTPS') === 'on'
            || $request->server('HTTP_X_FORWARDED_PROTO') === 'https'
            || $request->server('HTTP_X_FORWARDED_SSL') === 'on';

        if (option('force_ssl') || $isRequestSecure) {
            URL::forceScheme('https');
        }
    }
}
