export default {
  admin: {
    players: {
      list: () => '/admin/players/list' as const,
      delete: (player: number) => `/admin/players/${player}`,
      name: (player: number) => `/admin/players/${player}/name`,
      owner: (player: number) => `/admin/players/${player}/owner`,
      texture: (player: number) => `/admin/players/${player}/textures`,
    },
    users: {
      list: () => '/admin/users/list' as const,
      delete: (user: number) => `/admin/users/${user}`,
      email: (user: number) => `/admin/users/${user}/email`,
      nickname: (user: number) => `/admin/users/${user}/nickname`,
      password: (user: number) => `/admin/users/${user}/password`,
      permission: (user: number) => `/admin/users/${user}/permission`,
      score: (user: number) => `/admin/users/${user}/score`,
      verification: (user: number) => `/admin/users/${user}/verification`,
    },
  },
  auth: {
    bind: () => '/auth/bind' as const,
    forgot: () => '/auth/forgot' as const,
    login: () => '/auth/login' as const,
    logout: () => '/auth/logout' as const,
    register: () => '/auth/register' as const,
    reset: (uid: number) => `/auth/reset/${uid}`,
    verify: (uid: number) => `/auth/verify/${uid}`,
  },
  skinlib: {
    home: () => '/skinlib' as const,
    info: (tid: number) => `/skinlib/info/${tid}`,
    list: () => '/skinlib/list' as const,
    show: (tid: number) => `/skinlib/show/${tid}`,
    upload: () => '/skinlib/upload' as const,
  },
  user: {
    home: () => '/user' as const,
    closet: {
      add: () => '/user/closet' as const,
      page: () => '/user/closet' as const,
      ids: () => '/user/closet/ids' as const,
      list: () => '/user/closet/list' as const,
      remove: (tid: number) => `/user/closet/${tid}`,
      rename: (tid: number) => `/user/closet/${tid}`,
    },
    notification: (id: number) => `/user/notifications/${id}`,
    player: {
      page: () => '/user/player' as const,
      add: () => '/user/player/add' as const,
      bind: () => '/user/player/bind' as const,
      delete: (pid: number) => `/user/player/delete/${pid}`,
      list: () => '/user/player/list' as const,
      rename: (pid: number) => `/user/player/rename/${pid}`,
      set: (pid: number) => `/user/player/set/${pid}`,
      clear: (pid: number) => `/user/player/texture/clear/${pid}`,
    },
    profile: { avatar: () => '/user/profile/avatar' as const },
    score: () => '/user/score-info' as const,
    sign: () => '/user/sign' as const,
  },
}
