name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run tests
      run: touch ./storage/testing.sqlite && ./vendor/bin/phpunit
      env:
        APP_ENV: testing
        DB_CONNECTION: sqlite
        DB_DATABASE: storage/testing.sqlite
