name: CI

on: [push]

jobs:
  php73:
    name: 'PHP 7.3'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run tests
      run: |
        php -v
        touch ./storage/testing.sqlite
        ./vendor/bin/phpunit
      env:
        APP_ENV: testing
        DB_CONNECTION: sqlite
        DB_DATABASE: storage/testing.sqlite
  windows:
    name: 'Windows'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run tests
      run: |
        php.exe -v
        New-Item ./storage/testing.sqlite
        ./vendor/bin/phpunit
      env:
        APP_ENV: testing
        DB_CONNECTION: sqlite
        DB_DATABASE: storage/testing.sqlite
 frontend:
   name: Front End
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v1
   - name: Install dependencies
     run: yarn
   - name: Run tests
     run: |
       yarn lint
       yarn test
